<<<<<<< HEAD
# Generated by Django 3.2.8 on 2022-10-07 21:18
=======
# Generated by Django 4.1.2 on 2022-10-14 15:01
>>>>>>> 9201ffe7d08c22e0d022e1349cff7886c0014f86

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
