<<<<<<< HEAD
# Generated by Django 3.2.8 on 2022-10-07 21:24
=======
# Generated by Django 4.1.2 on 2022-10-14 15:11
>>>>>>> 9201ffe7d08c22e0d022e1349cff7886c0014f86

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questiontext',
            new_name='question_text',
        ),
    ]
