# Generated by Django 4.1.2 on 2022-10-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questiontext',
            new_name='question_text',
        ),
    ]
